//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommandAS.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommandAS.Tools.ToolsRes", typeof(ToolsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жирный.
        /// </summary>
        internal static string fBold {
            get {
                return ResourceManager.GetString("fBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать в буфер обмена.
        /// </summary>
        internal static string fCopy {
            get {
                return ResourceManager.GetString("fCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вырезать в буфер обмена.
        /// </summary>
        internal static string fCut {
            get {
                return ResourceManager.GetString("fCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение шрифта.
        /// </summary>
        internal static string fFontChange {
            get {
                return ResourceManager.GetString("fFontChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсив.
        /// </summary>
        internal static string fItalic {
            get {
                return ResourceManager.GetString("fItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выравнивание по центру.
        /// </summary>
        internal static string fJustifyCenter {
            get {
                return ResourceManager.GetString("fJustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выравнивание по левому краю.
        /// </summary>
        internal static string fJustifyLeft {
            get {
                return ResourceManager.GetString("fJustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выравнивание по правому краю.
        /// </summary>
        internal static string fJustifyRight {
            get {
                return ResourceManager.GetString("fJustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новый документ.
        /// </summary>
        internal static string fNew {
            get {
                return ResourceManager.GetString("fNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть документ.
        /// </summary>
        internal static string fOpen {
            get {
                return ResourceManager.GetString("fOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить из буфера обмена.
        /// </summary>
        internal static string fPaste {
            get {
                return ResourceManager.GetString("fPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печатать документ.
        /// </summary>
        internal static string fPrint {
            get {
                return ResourceManager.GetString("fPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный просмотр документа.
        /// </summary>
        internal static string fPrintPreview {
            get {
                return ResourceManager.GetString("fPrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительный просмотр.
        /// </summary>
        internal static string fPrintPreviewText {
            get {
                return ResourceManager.GetString("fPrintPreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печатать текст.
        /// </summary>
        internal static string fPrintText {
            get {
                return ResourceManager.GetString("fPrintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуть последнюю операцию.
        /// </summary>
        internal static string fRedo {
            get {
                return ResourceManager.GetString("fRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить документ.
        /// </summary>
        internal static string fSave {
            get {
                return ResourceManager.GetString("fSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка орфографии.
        /// </summary>
        internal static string fSpellChecker {
            get {
                return ResourceManager.GetString("fSpellChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подчеркивание.
        /// </summary>
        internal static string fUnderline {
            get {
                return ResourceManager.GetString("fUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена последней операции.
        /// </summary>
        internal static string fUndo {
            get {
                return ResourceManager.GetString("fUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiBborder {
            get {
                object obj = ResourceManager.GetObject("iiBborder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiBold {
            get {
                object obj = ResourceManager.GetObject("iiBold", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiBullets {
            get {
                object obj = ResourceManager.GetObject("iiBullets", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiBulletsNum {
            get {
                object obj = ResourceManager.GetObject("iiBulletsNum", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiColorBack {
            get {
                object obj = ResourceManager.GetObject("iiColorBack", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiColorFont {
            get {
                object obj = ResourceManager.GetObject("iiColorFont", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiConvert {
            get {
                object obj = ResourceManager.GetObject("iiConvert", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiCopy {
            get {
                object obj = ResourceManager.GetObject("iiCopy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiCut {
            get {
                object obj = ResourceManager.GetObject("iiCut", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiHyper {
            get {
                object obj = ResourceManager.GetObject("iiHyper", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiHyper2 {
            get {
                object obj = ResourceManager.GetObject("iiHyper2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiHyper3 {
            get {
                object obj = ResourceManager.GetObject("iiHyper3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiIndentLeft {
            get {
                object obj = ResourceManager.GetObject("iiIndentLeft", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiIndentRight {
            get {
                object obj = ResourceManager.GetObject("iiIndentRight", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiItalic {
            get {
                object obj = ResourceManager.GetObject("iiItalic", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiJustifyCenter {
            get {
                object obj = ResourceManager.GetObject("iiJustifyCenter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiJustifyFull {
            get {
                object obj = ResourceManager.GetObject("iiJustifyFull", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiJustifyLeft {
            get {
                object obj = ResourceManager.GetObject("iiJustifyLeft", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiJustifyRight {
            get {
                object obj = ResourceManager.GetObject("iiJustifyRight", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiNew {
            get {
                object obj = ResourceManager.GetObject("iiNew", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiOpen {
            get {
                object obj = ResourceManager.GetObject("iiOpen", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiPaste {
            get {
                object obj = ResourceManager.GetObject("iiPaste", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiPreview {
            get {
                object obj = ResourceManager.GetObject("iiPreview", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiPrint {
            get {
                object obj = ResourceManager.GetObject("iiPrint", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiRedo {
            get {
                object obj = ResourceManager.GetObject("iiRedo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiSave {
            get {
                object obj = ResourceManager.GetObject("iiSave", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiSizeFonts {
            get {
                object obj = ResourceManager.GetObject("iiSizeFonts", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiStyle {
            get {
                object obj = ResourceManager.GetObject("iiStyle", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiTable {
            get {
                object obj = ResourceManager.GetObject("iiTable", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiUnderline {
            get {
                object obj = ResourceManager.GetObject("iiUnderline", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon iiUndo {
            get {
                object obj = ResourceManager.GetObject("iiUndo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жирный.
        /// </summary>
        internal static string sBold {
            get {
                return ResourceManager.GetString("sBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Копировать.
        /// </summary>
        internal static string sCopy {
            get {
                return ResourceManager.GetString("sCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вырезать.
        /// </summary>
        internal static string sCut {
            get {
                return ResourceManager.GetString("sCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шрифт.
        /// </summary>
        internal static string sFontChange {
            get {
                return ResourceManager.GetString("sFontChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсив.
        /// </summary>
        internal static string sItalic {
            get {
                return ResourceManager.GetString("sItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По центру.
        /// </summary>
        internal static string sJustifyCenter {
            get {
                return ResourceManager.GetString("sJustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В лево.
        /// </summary>
        internal static string sJustifyLeft {
            get {
                return ResourceManager.GetString("sJustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В право.
        /// </summary>
        internal static string sJustifyRight {
            get {
                return ResourceManager.GetString("sJustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        internal static string sNew {
            get {
                return ResourceManager.GetString("sNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        internal static string sOpen {
            get {
                return ResourceManager.GetString("sOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вставить.
        /// </summary>
        internal static string sPaste {
            get {
                return ResourceManager.GetString("sPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Spelling {
            get {
                object obj = ResourceManager.GetObject("Spelling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Печать.
        /// </summary>
        internal static string sPrint {
            get {
                return ResourceManager.GetString("sPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        internal static string sPrintPreview {
            get {
                return ResourceManager.GetString("sPrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вернуть.
        /// </summary>
        internal static string sRedo {
            get {
                return ResourceManager.GetString("sRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string sSave {
            get {
                return ResourceManager.GetString("sSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подчеркивание.
        /// </summary>
        internal static string sUnderline {
            get {
                return ResourceManager.GetString("sUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        internal static string sUndo {
            get {
                return ResourceManager.GetString("sUndo", resourceCulture);
            }
        }
    }
}
